### ISSUE TITLE
deploymentmanager-samples/examples/v2/gke/jinja/replicatedservice.yaml -- fails creation and deletion

### ISSUE THREAD

**Issue by joshpadilla** [GoogleCloudPlatform/deploymentmanager-samples#65]
Using this replication service template YAML and Jinja fails. The creation failing I could understand, maybe I made a mistake. But now the failed replication service is stuck in my Deployment manager and I cannot remove it:

Timeout after 180000 ms when fetching URL https://35.199.152.98/api/v1/namespaces/default/replicationcontrollers/gke-quickflask-repl-service-v1-replicated-service-v1-rc, reason: TIMEOUT_WEB
gke-quickflask-repl-service-v1 has resource warnings
gke-quickflask-repl-service-v1-replicated-service-v1-rc: Timeout after 180000 ms when fetching URL https://35.199.152.98/api/v1/namespaces/default/replicationcontrollers/gke-quickflask-repl-service-v1-replicated-service-v1-rc, reason: TIMEOUT_WEB

It would seem a replication controller and service could be handled by Kubernetes itself (with kubectl and Kubernetes based YAML templates, not necessarily by GKE. In any case, this seems like a bug.

#Kubernetes replication service template
#DEPLOY Kubernetes replication service
#gcloud deployment-manager deployments create gke-quickflask-repl-service-v1 --config replicatedservice.yaml
#
#kubectl delete replicationcontroller gke-quickflask-repl-service-v1
#
#gcloud deployment-manager deployments delete gke-quickflask-repl-service-v1
imports:
- path: replicatedservice.jinja

resources:
- name: replicated-service-v1
  type: replicatedservice.jinja
  properties:
    clusterType: gke-cluster-demo-v1-type
    image: gcr.io/$PROJECT_ID/quickflask-image:v1

**Comment by aljim** [comment]
This should be fixed now, can you retry?

**Comment by joshpadilla** [comment]
I sent some errors for debug via email. I don't think it's fixed quite yet, b/c I still can't delete the replication controller from my GCP project in the GCP console.
